import re
import sys

"""gets its input from a JackTokenizer and emits its output to an output file
Output generated by a series of compile_xxx methods, one for almost all non-terminal rule xxx 
(except no markup for type, className, subroutineName, varName, statement, subroutineCall)
Out of 21 non-terminal grammar rules, there are 15 compile_xxx methods.
For the 6 remaining, the parsing logic is handled by rules that invoke them
Each of 15 methods handles all tokens that make up xxx,
advancing the tokenizer exactly beyond these tokens, and outputs the parsing of xxx
parsing logic of each method follows the right-hand side of the rule that it implements

First build basic version that handles everything 
except expressions and array-oriented statements
then add them"""


class CompilationEngine:

    def __init__(self, input, output):
        """creates a new compilation engine with given input and output
        Next routine called is compile_class"""
        self.tokenizer = input
        self.target = output
        # self.current_token = self.tokenizer.current_token[1]

    def compile_class(self):
        """compiles complete class using 2 loops for
        compile_class_var_dec and compile_subroutine_dec"""
        self.target.write("<class>\n")
        self.__process("class")
        if self.tokenizer.token_type() == self.tokenizer.IDENTIFIER:
            self.__process(self.current_token)
        else:
            raise ValueError(f"Expected className identifier, got {self.current_token}")
        self.__process("{")

        while True:
            if self.current_token in ["static", "field"]:
                self.compile_class_var_dec()
            else:
                break

        while True:
            if self.current_token in ["constructor", "function", "method"]:
                self.compile_subroutine_dec()
            else:
                break
        self.__process("}")
        self.target.write("</class>\n")

    def compile_class_var_dec(self):
        """compiles a static variable or field declaration
        use a loop for handling all the variable declarations"""
        self.target.write("<classVarDec>\n")
        # already know that current_token is static|field
        self.__process(self.current_token)
        self.__handle_type()
        if self.tokenizer.token_type() == self.tokenizer.IDENTIFIER:
            self.__process(self.current_token)
        else:
            raise ValueError(f"Expected varName identifier, got {self.current_token}")

        while True:
            if self.current_token == ",":
                self.__process(",")
                self.__handle_var_name()
            else:
                break
        self.__process(";")
        self.target.write("</classVarDec>\n")

    def compile_subroutine_dec(self):
        """compiles a complete method, function or constructor"""
        self.target.write("<subroutineDec>\n")
        # already know that current_token is constructor|function|method
        self.__process(self.current_token)

        if (
            self.current_token in ["int", "char", "boolean", "void"]
            or self.tokenizer.token_type() == self.tokenizer.IDENTIFIER
        ):
            self.__process(self.current_token)
        else:
            raise ValueError(
                f"Expected type int, char, boolean, className or void, got {self.current_token}"
            )

        self.__handle_subroutine_name()
        self.__process("(")
        self.compile_parameter_list()
        self.__process(")")
        self.compile_subroutine_body()
        self.target.write("</subroutineDec>\n")

    def compile_parameter_list(self):
        """compiles (possibly empty) parameter list
        Does not handle enclosing '()'"""
        self.target.write("<parameterList>\n")
        # we reach end of parameter list when current token is )
        while self.current_token != ")":
            # handle multiple parameters separated by ,
            if self.current_token == ",":
                self.__process(",")
                continue
            self.__handle_type()
            self.__handle_var_name()
        self.target.write("</parameterList>\n")

    def compile_subroutine_body(self):
        """compiles subroutine's body"""
        self.target.write("<subroutineBody>\n")
        self.__process("{")
        while self.current_token == "var":
            self.compile_var_dec()
        self.compile_statements()
        self.__process("}")
        self.target.write("</subroutineBody>\n")

    def compile_var_dec(self):
        """compiles a var declaration'"""
        self.target.write("<varDec>\n")
        # already know that current_token is var
        self.__process(self.current_token)
        self.__handle_type()
        self.__handle_var_name()
        while self.current_token == ",":
            self.__process(",")
            self.__handle_var_name()
        self.__process(";")
        self.target.write("</varDec>\n")

    def compile_statements(self):
        """compiles a sequence of statements
        Does not handle enclosing '{}'
        Uses loop to handle 0 or more statement, then
        invokes specific compile_if etc. depending of left-most token ('if')"""
        self.target.write("<statements>\n")
        while self.current_token in ["if", "let", "while", "do", "return"]:
            if self.current_token == "if":
                self.compile_if()
            elif self.current_token == "let":
                self.compile_let()
            elif self.current_token == "while":
                self.compile_while()
            elif self.current_token == "do":
                self.compile_do()
            elif self.current_token == "return":
                self.compile_return()
        self.target.write("</statements>\n")

    def compile_let(self):
        """compiles a let statement"""
        self.target.write("<letStatement>\n")
        self.__process("let")
        self.__handle_var_name()
        if self.current_token == "[":
            self.__process("[")
            self.compile_expression()
            self.__process("]")
        self.__process("=")
        self.compile_expression()
        self.__process(";")
        self.target.write("</letStatement>\n")

    def compile_if(self):
        """compiles an if statement, possibly with trailing else clause"""
        self.target.write("<ifStatement>\n")
        self.__process("if")
        self.__process("(")
        self.compile_expression()
        self.__process(")")
        self.__process("{")
        self.compile_statements()
        self.__process("}")
        # optional else clause
        if self.current_token == "else":
            self.__process("else")
            self.__process("{")
            self.compile_statements()
            self.__process("}")
        self.target.write("</ifStatement>\n")

    def compile_while(self):
        """compiles a while statement
        Should be called if current token is 'while'"""
        self.target.write("<whileStatement>\n")
        self.__process("while")
        self.__process("(")
        self.compile_expression()
        self.__process(")")
        self.__process("{")
        self.compile_statements()
        self.__process("}")
        self.target.write("</whileStatement>\n")

    def compile_do(self):
        """compiles do statement"""
        self.target.write("<doStatement>\n")
        self.__process("do")

        # do subroutineCall statement parsed as if their syntax were do expression
        # wraps subroutineCall with <expression><term> ... </term></expression>
        # self.compile_expression()

        if self.tokenizer.token_type() == self.tokenizer.IDENTIFIER:
            # look ahead
            current = self.current_token
            self.tokenizer.advance()
            token_ahead = self.tokenizer.current_token[1]
            self.target.write(f"<identifier> {current} </identifier>\n")

            # subroutineCall: subroutineName '(' expressionList ')'
            if token_ahead == "(":
                self.__process("(")
                self.compile_expression_list()
                self.__process(")")

            # subroutineCall: className|varName '.' subroutineName '(' expressionList ')'
            elif token_ahead == ".":
                self.__process(".")
                self.__handle_subroutine_name()
                self.__process("(")
                self.compile_expression_list()
                self.__process(")")
        else:
            raise ValueError(
                f"Expected subroutineName|className|varName identifier, got {self.current_token}"
            )

        self.__process(";")
        self.target.write("</doStatement>\n")

    def compile_return(self):
        """compiles a return statement"""
        self.target.write("<returnStatement>\n")
        self.__process("return")
        # optional expression
        if self.current_token != ";":
            self.compile_expression()
        self.__process(";")
        self.target.write("</returnStatement>\n")

    def compile_expression(self):
        """compiles an expression"""
        self.target.write("<expression>\n")
        self.compile_term()
        # optional pair op term
        if self.current_token in [
            "+",
            "-",
            "*",
            "/",
            "&amp;",
            "|",
            "&lt;",
            "&gt;",
            "=",
        ]:
            self.__process(self.current_token)
            self.compile_term()
        self.target.write("</expression>\n")

    def compile_term(self):
        """compiles a term
        If current token is identifier, must distinguish between variable,
        an array entry, or a subroutine call.
        term: integerConstant|stringConstant|keywordConstant|
        '(' expression ')'| unaryOp term |
        varName|varName '[' expression ']'|subroutineCall
        A single look-ahead token, which may be one of '[', '(' or '.'
        suffices to distinguish between the possibilities.
        Any other token is not part of this term and should not be advanced over."""
        self.target.write("<term>\n")
        # '(' expression ')'
        if self.current_token == "(":
            self.__process("(")
            self.compile_expression()
            self.__process(")")
        # unaryOp term
        elif self.current_token in ["-", "~"]:
            self.__process(self.current_token)
            self.compile_term()
        # integerConstant|stringConstant|keywordConstant
        elif self.tokenizer.token_type() in [
            self.tokenizer.INT_CONST,
            self.tokenizer.STRING_CONST,
            self.tokenizer.KEYWORD,
        ]:
            self.__process(self.current_token)
        # identifier
        elif self.tokenizer.token_type() == self.tokenizer.IDENTIFIER:
            # look ahead
            current = self.current_token
            self.tokenizer.advance()
            token_ahead = self.tokenizer.current_token[1]
            self.target.write(f"<identifier> {current} </identifier>\n")

            # varName '[' expression ']'
            if token_ahead == "[":
                self.__process("[")
                self.compile_expression()
                self.__process("]")

            # subroutineCall: subroutineName '(' expressionList ')'
            elif token_ahead == "(":
                self.__process("(")
                self.compile_expression_list()
                self.__process(")")

            # subroutineCall: className|varName '.' subroutineName '(' expressionList ')'
            elif token_ahead == ".":
                self.__process(".")
                self.__handle_subroutine_name()
                self.__process("(")
                self.compile_expression_list()
                self.__process(")")
            # varName
            # Any other token is not part of this term and should not be advanced over.
            else:
                self.current_token = token_ahead

        self.target.write("</term>\n")

    def compile_expression_list(self) -> int:
        """compiles (possibly empty) comma-separated list of expressions
        Returns the number of expressions in the list"""
        self.target.write("<expressionList>\n")
        # at least one expression as argument
        counter_expressions = 0
        if self.current_token != ")":
            self.compile_expression()
            counter_expressions += 1
        # optional multiple expressions separated by ,
        while self.current_token == ",":
            self.__process(",")
            self.compile_expression()
            counter_expressions += 1
        self.target.write("</expressionList>\n")

        return counter_expressions

    def __handle_type(self):
        if (
            self.current_token in ["int", "char", "boolean"]
            or self.tokenizer.token_type() == self.tokenizer.IDENTIFIER
        ):
            self.__process(self.current_token)
        else:
            raise ValueError(
                f"Expected type int, char, boolean or className identifier, got {self.current_token}"
            )

    def __handle_var_name(self):
        if self.tokenizer.token_type() == self.tokenizer.IDENTIFIER:
            self.__process(self.current_token)
        else:
            raise ValueError(f"Expected varName identifier, got {self.current_token}")

    def __handle_subroutine_name(self):
        if self.tokenizer.token_type() == self.tokenizer.IDENTIFIER:
            self.__process(self.current_token)
        else:
            raise ValueError(
                f"Expected subroutineName identifier, got {self.current_token}"
            )

    def __process(self, token: str):
        """helper routine that handles current token,
        and advances to get the next token"""
        # expect to see token
        if self.tokenizer.current_token[1] == token:
            self.__write_xml_token(token)
        else:
            raise ValueError(f"Expected {self.tokenizer.current_token[1]}, got {token}")
        # gets next token, advance the input
        self.tokenizer.advance()
        if self.tokenizer.current_token:
            self.current_token = self.tokenizer.current_token[1]
        # reached EOF
        else:
            self.current_token = None

    def __write_xml_token(self, token: str):
        """helper routine that writes XML for current token
        e.g.<keyword> while </keyword>
        or <symbol> + </symbol>"""
        tag = self.tokenizer.tags[self.tokenizer.token_type()]
        self.target.write(f"<{tag}> {token} </{tag}>\n")
